// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservations.API.Infrastructure;

#nullable disable

namespace Reservations.API.Migrations
{
    [DbContext(typeof(ReservationsContext))]
    [Migration("20240710163656_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reservations.API.Core.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfReservation")
                        .HasColumnType("datetime2");

                    b.Property<double>("SumPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservationId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("Reservations.API.Core.Reservation", b =>
                {
                    b.OwnsMany("Reservations.API.Core.ReservationComponent", "ReservationComponents", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("SerialNumber")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("SerialNumber"));

                            b1.Property<int>("NumberOfTickets")
                                .HasColumnType("int");

                            b1.Property<double>("Price")
                                .HasColumnType("float");

                            b1.Property<Guid>("SportingEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("SumComponentPrice")
                                .HasColumnType("float");

                            b1.HasKey("ReservationId", "SerialNumber");

                            b1.ToTable("ReservationComponent");

                            b1.WithOwner("Reservation")
                                .HasForeignKey("ReservationId");

                            b1.Navigation("Reservation");
                        });

                    b.Navigation("ReservationComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
